# -*- coding: utf-8 -*-
"""Entity Analyzer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FRfrIRqZ-BH1NmKJpwGOMOOo6T0jeF2-
"""

!pip install requests
!pip install beautifulsoup4
!pip install spacy
!pip install matplotlib
import streamlit as st
import requests
from bs4 import BeautifulSoup
import spacy
import matplotlib.pyplot as plt

nlp = spacy.load("en_core_web_sm")

def clean_and_lemmatize(html):
    # Use BeautifulSoup to extract the text from the HTML content
    soup = BeautifulSoup(html, "html.parser")
    text = soup.get_text()

    # Use spacy to tokenize the text and lemmatize the tokens
    doc = nlp(text)
    lemmas = [token.lemma_ for token in doc]

    # Return the cleaned and lemmatized text
    return " ".join(lemmas)

def analyze_entities(text):
    # Use spacy to tokenize the text and extract entities
    doc = nlp(text)
    entities = [(entity.text, entity.label_) for entity in doc.ents]

    # Return the list of entities
    return entities

st.title("Entity Comparison Tool")

# Get the URLs from the user input
url1 = st.text_input("Enter the first URL:")
url2 = st.text_input("Enter the second URL:")

# Fetch the HTML content from each URL
html1 = requests.get(url1).text
html2 = requests.get(url2).text

if st.button("Compare Entities"):
    # Clean and lemmatize the HTML content from each URL
    text1 = clean_and_lemmatize(html1)
    text2 = clean_and_lemmatize(html2)
